"""Update HeistHistory for PostgreSQL JSON

Revision ID: 0841f8533578
Revises: 36971c084fec
Create Date: 2025-12-24 14:37:56.764918

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0841f8533578'
down_revision = '36971c084fec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heist_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('timestamp')
        batch_op.drop_column('participants_names')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('heist_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participants_names', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('participants_snapshot')

    # ### end Alembic commands ###
