"""add gang chat and private chat tables

Revision ID: 14db83577c98
Revises: 7f8e9d0a1b2c
Create Date: 2026-01-13 13:09:58.921770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14db83577c98'
down_revision = '7f8e9d0a1b2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gang_chat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(length=500), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('gang_chat', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gang_chat_created_at'),
            ['created_at'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_gang_chat_gang_id'),
            ['gang_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_gang_chat_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('private_chat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(length=1000), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('deleted_by_sender', sa.Boolean(), nullable=True),
                    sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('private_chat', schema=None) as batch_op:
        batch_op.create_index(
            'idx_private_chat_conversation', [
                'sender_id', 'receiver_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_private_chat_created_at'),
            ['created_at'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_private_chat_receiver_id'),
            ['receiver_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_private_chat_sender_id'),
            ['sender_id'],
            unique=False)

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_crime_cooldown'),
            ['cooldown'],
            unique=False)

    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.create_index(
            'idx_crime_lobby_status_created', [
                'status', 'created_at'], unique=False)

    with op.batch_alter_table('futures_position', schema=None) as batch_op:
        batch_op.create_index(
            'idx_futures_liq_check', [
                'asset_id', 'is_open', 'position_type', 'liquidation_price'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_futures_position_position_type'),
            ['position_type'],
            unique=False)

    with op.batch_alter_table('public_chat', schema=None) as batch_op:
        batch_op.drop_index('idx_public_chat_created_at')
        batch_op.create_index(
            batch_op.f('ix_public_chat_created_at'),
            ['created_at'],
            unique=False)

    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.create_index(
            'idx_spot_order_exec_buy', [
                'asset_id', 'status', 'order_type', 'price'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('jail_escape_attempts',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('jail_gilboa_attempts',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('gym_sessions_count',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('gym_speedups_count',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_server_default=sa.text('0'))
        batch_op.create_index(
            batch_op.f('ix_user_chat_muted_until'),
            ['chat_muted_until'],
            unique=False)

    with op.batch_alter_table('user_crime_cooldown', schema=None) as batch_op:
        batch_op.create_index(
            'idx_user_crime_cooldown_user_crime', [
                'user_id', 'crime_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_crime_cooldown_crime_id'),
            ['crime_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_crime_cooldown_user_id'),
            ['user_id'],
            unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_crime_cooldown', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_crime_cooldown_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_crime_cooldown_crime_id'))
        batch_op.drop_index('idx_user_crime_cooldown_user_crime')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_chat_muted_until'))
        batch_op.alter_column('gym_speedups_count',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('gym_sessions_count',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('jail_gilboa_attempts',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text('0'))
        batch_op.alter_column('jail_escape_attempts',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_server_default=sa.text('0'))

    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.drop_index('idx_spot_order_exec_buy')

    with op.batch_alter_table('public_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_chat_created_at'))
        batch_op.create_index(
            'idx_public_chat_created_at',
            ['created_at'],
            unique=False)

    with op.batch_alter_table('futures_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_futures_position_position_type'))
        batch_op.drop_index('idx_futures_liq_check')

    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.drop_index('idx_crime_lobby_status_created')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_cooldown'))

    with op.batch_alter_table('private_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_private_chat_sender_id'))
        batch_op.drop_index(batch_op.f('ix_private_chat_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_private_chat_created_at'))
        batch_op.drop_index('idx_private_chat_conversation')

    op.drop_table('private_chat')
    with op.batch_alter_table('gang_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_gang_chat_gang_id'))
        batch_op.drop_index(batch_op.f('ix_gang_chat_created_at'))

    op.drop_table('gang_chat')
    # ### end Alembic commands ###
