"""Add more indexes for social and logs

Revision ID: 36971c084fec
Revises: f3437c161fa2
Create Date: 2025-12-24 12:57:57.009382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36971c084fec'
down_revision = 'f3437c161fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_log_admin_id'), ['admin_id'], unique=False)

    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_leader_id'), ['leader_id'], unique=False)

    with op.batch_alter_table('gang_invite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_invite_gang_id'), ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_invite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    with op.batch_alter_table('gang_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_invite_user_id'))
        batch_op.drop_index(batch_op.f('ix_gang_invite_gang_id'))

    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_leader_id'))

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_log_admin_id'))

    # ### end Alembic commands ###
