"""initial_comprehensive_schema

Revision ID: 380a7cb143ee
Revises:
Create Date: 2026-01-02 16:48:32.353632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '380a7cb143ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'achievement',
        sa.Column(
            'id',
            sa.Integer(),
            nullable=False),
        sa.Column(
            'key',
            sa.String(
                length=64),
            nullable=False),
        sa.Column(
            'title',
            sa.String(
                length=128),
            nullable=False),
        sa.Column(
            'description',
            sa.String(
                length=255),
            nullable=True),
        sa.Column(
            'points',
            sa.Integer(),
            nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(),
            nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('key'))
    op.create_table('announcement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('daily_task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=False),
                    sa.Column('target_type', sa.String(length=50), nullable=False),
                    sa.Column('target_count', sa.Integer(), nullable=True),
                    sa.Column('reward_money', sa.Integer(), nullable=True),
                    sa.Column('reward_exp', sa.Integer(), nullable=True),
                    sa.Column('min_level', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('economy_snapshot',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('total_money', sa.BigInteger(), nullable=True),
                    sa.Column('total_bank', sa.BigInteger(), nullable=True),
                    sa.Column('avg_wealth', sa.BigInteger(), nullable=True),
                    sa.Column('top_1_percent_share', sa.Float(), nullable=True),
                    sa.Column('active_users_24h', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('economy_snapshot', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_economy_snapshot_date'),
            ['date'],
            unique=False)

    op.create_table('forum_category',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('min_rank', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('gang',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('leader_id', sa.Integer(), nullable=False),
                    sa.Column('underboss_id', sa.Integer(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('exp', sa.Integer(), nullable=True),
                    sa.Column('money', sa.Integer(), nullable=True),
                    sa.Column('bullets', sa.Integer(), nullable=True),
                    sa.Column('max_members', sa.Integer(), nullable=True),
                    sa.Column('min_level_req', sa.Integer(), nullable=True),
                    sa.Column('recruitment_status', sa.String(length=20), nullable=True),
                    sa.Column('allowed_countries', sa.String(length=255), nullable=True),
                    sa.Column('upgrades', sa.Text(), nullable=True),
                    sa.Column('last_organized_crime_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], name='fk_gang_leader_id', use_alter=True),
                    sa.ForeignKeyConstraint(['underboss_id'], ['user.id'], name='fk_gang_underboss_id', use_alter=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gang_leader_id'),
            ['leader_id'],
            unique=False)

    op.create_table('heist_history',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('crime_name', sa.String(length=100), nullable=True),
                    sa.Column('leader_name', sa.String(length=64), nullable=True),
                    sa.Column('participants_snapshot', postgresql.JSON(astext_type=sa.Text()), nullable=True),
                    sa.Column('success', sa.Boolean(), nullable=True),
                    sa.Column('money_earned', sa.Integer(), nullable=True),
                    sa.Column('exp_earned', sa.Integer(), nullable=True),
                    sa.Column('log_details', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('cost', sa.Integer(), nullable=True),
                    sa.Column('is_black_market', sa.Boolean(), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('bonus_strength', sa.Integer(), nullable=True),
                    sa.Column('bonus_defense', sa.Integer(), nullable=True),
                    sa.Column('bonus_agility', sa.Integer(), nullable=True),
                    sa.Column('ammo_needed', sa.Integer(), nullable=True),
                    sa.Column('recover_energy', sa.Integer(), nullable=True),
                    sa.Column('recover_health', sa.Integer(), nullable=True),
                    sa.Column('recover_brave', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('learning_logs',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('user_question', sa.Text(), nullable=False),
                    sa.Column('ai_response', sa.Text(), nullable=False),
                    sa.Column('was_helpful', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('location',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('cost', sa.Integer(), nullable=True),
                    sa.Column('cooldown', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.Column('specialty', sa.String(length=50), nullable=True),
                    sa.Column('specialty_value', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('market_asset',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbol', sa.String(length=10), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('asset_type', sa.String(length=20), nullable=True),
                    sa.Column('current_price', sa.Float(), nullable=True),
                    sa.Column('price_change_24h', sa.Float(), nullable=True),
                    sa.Column('high_24h', sa.Float(), nullable=True),
                    sa.Column('low_24h', sa.Float(), nullable=True),
                    sa.Column('volume_24h', sa.Float(), nullable=True),
                    sa.Column('last_updated', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('symbol')
                    )
    op.create_table('organized_crime',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('min_level', sa.Integer(), nullable=True),
                    sa.Column('min_members', sa.Integer(), nullable=True),
                    sa.Column('max_members', sa.Integer(), nullable=True),
                    sa.Column('duration_minutes', sa.Integer(), nullable=True),
                    sa.Column('planning_time_seconds', sa.Integer(), nullable=True),
                    sa.Column('cooldown_hours', sa.Integer(), nullable=True),
                    sa.Column('energy_cost', sa.Integer(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('money_reward_min', sa.Integer(), nullable=True),
                    sa.Column('money_reward_max', sa.Integer(), nullable=True),
                    sa.Column('exp_reward', sa.Integer(), nullable=True),
                    sa.Column('requirements', sa.Text(), nullable=True),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.Column('roles_config', postgresql.JSON(astext_type=sa.Text()), nullable=True),
                    sa.Column('min_gang_level', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('security_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('event_type', sa.String(length=50), nullable=False),
                    sa.Column('ip_address', sa.String(length=50), nullable=True),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('system_config',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=50), nullable=False),
                    sa.Column('value', sa.Text(), nullable=True),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('key')
                    )
    op.create_table('user_rank',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('min_level', sa.Integer(), nullable=True),
                    sa.Column('resurrection_cost', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('min_level')
                    )
    op.create_table('vehicle',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('speed', sa.Integer(), nullable=True),
                    sa.Column('defense', sa.Integer(), nullable=True),
                    sa.Column('risk', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('video_scenarios',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=128), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('script_json', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('crime',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.String(length=255), nullable=True),
                    sa.Column('energy_cost', sa.Integer(), nullable=True),
                    sa.Column('money_reward_min', sa.Integer(), nullable=True),
                    sa.Column('money_reward_max', sa.Integer(), nullable=True),
                    sa.Column('exp_reward', sa.Integer(), nullable=True),
                    sa.Column('min_level', sa.Integer(), nullable=True),
                    sa.Column('cooldown', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(length=100), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('reward_type', sa.String(length=20), nullable=True),
                    sa.Column('reward_item_id', sa.Integer(), nullable=True),
                    sa.Column('min_strength', sa.Integer(), nullable=True),
                    sa.Column('min_agility', sa.Integer(), nullable=True),
                    sa.Column('min_intelligence', sa.Integer(), nullable=True),
                    sa.Column('daily_limit', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['reward_item_id'], ['item.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('gang_alliance',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang1_id', sa.Integer(), nullable=False),
                    sa.Column('gang2_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['gang1_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['gang2_id'], ['gang.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('gang_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('gang_item', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gang_item_gang_id'),
            ['gang_id'],
            unique=False)

    op.create_table('gang_war',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang1_id', sa.Integer(), nullable=False),
                    sa.Column('gang2_id', sa.Integer(), nullable=False),
                    sa.Column('score_gang1', sa.Integer(), nullable=True),
                    sa.Column('score_gang2', sa.Integer(), nullable=True),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('war_type', sa.String(length=50), nullable=True),
                    sa.Column('winner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['gang1_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['gang2_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['winner_id'], ['gang.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('username', sa.String(length=64), nullable=False),
                    sa.Column('password_hash', sa.String(length=256), nullable=True),
                    sa.Column('role', sa.Enum('GUEST', 'USER', 'SUBSCRIBER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN', 'DEVELOPER', name='userrole'), nullable=True),
                    sa.Column('avatar', sa.String(length=100), nullable=True),
                    sa.Column('country', sa.String(length=2), nullable=True),
                    sa.Column('email', sa.String(length=120), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=True),
                    sa.Column('verified_on', sa.DateTime(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('exp', sa.BigInteger(), nullable=True),
                    sa.Column('money', sa.BigInteger(), nullable=True),
                    sa.Column('bullets', sa.BigInteger(), nullable=True),
                    sa.Column('diamonds', sa.BigInteger(), nullable=True),
                    sa.Column('energy', sa.BigInteger(), nullable=True),
                    sa.Column('max_energy', sa.BigInteger(), nullable=True),
                    sa.Column('health', sa.Integer(), nullable=True),
                    sa.Column('max_health', sa.Integer(), nullable=True),
                    sa.Column('brave', sa.Integer(), nullable=True),
                    sa.Column('max_brave', sa.Integer(), nullable=True),
                    sa.Column('strength', sa.Integer(), nullable=True),
                    sa.Column('defense', sa.Integer(), nullable=True),
                    sa.Column('agility', sa.Integer(), nullable=True),
                    sa.Column('intelligence', sa.Integer(), nullable=True),
                    sa.Column('driving_skill', sa.Integer(), nullable=True),
                    sa.Column('bank_balance', sa.BigInteger(), nullable=True),
                    sa.Column('jail_until', sa.DateTime(), nullable=True),
                    sa.Column('hospital_until', sa.DateTime(), nullable=True),
                    sa.Column('daily_money_earned', sa.BigInteger(), nullable=True),
                    sa.Column('daily_money_date', sa.Date(), nullable=True),
                    sa.Column('daily_bullets_purchased', sa.Integer(), nullable=True),
                    sa.Column('gym_until', sa.DateTime(), nullable=True),
                    sa.Column('gym_activity', sa.String(length=512), nullable=True),
                    sa.Column('is_safe_house_active', sa.Boolean(), nullable=True),
                    sa.Column('safe_house_until', sa.DateTime(), nullable=True),
                    sa.Column('is_admin_protected', sa.Boolean(), nullable=True),
                    sa.Column('heat_points', sa.Integer(), nullable=True),
                    sa.Column('heat_updated_at', sa.DateTime(), nullable=True),
                    sa.Column('is_disguised', sa.Boolean(), nullable=True),
                    sa.Column('disguise_until', sa.DateTime(), nullable=True),
                    sa.Column('casino_luck_until', sa.DateTime(), nullable=True),
                    sa.Column('active_hostess_id', sa.Integer(), nullable=True),
                    sa.Column('version', sa.Integer(), nullable=False),
                    sa.Column('is_ghost_mode', sa.Boolean(), nullable=True),
                    sa.Column('banned_until', sa.DateTime(), nullable=True),
                    sa.Column('ban_reason', sa.String(length=255), nullable=True),
                    sa.Column('is_suspicious', sa.Boolean(), nullable=True),
                    sa.Column('gang_id', sa.Integer(), nullable=True),
                    sa.Column('location_id', sa.Integer(), nullable=True),
                    sa.Column('referral_code', sa.String(length=16), nullable=True),
                    sa.Column('referred_by_id', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_daily_reward', sa.DateTime(), nullable=True),
                    sa.Column('daily_streak', sa.Integer(), nullable=True),
                    sa.Column('last_chase', sa.DateTime(), nullable=True),
                    sa.Column('crime_cooldown_until', sa.DateTime(), nullable=True),
                    sa.Column('last_crime', sa.DateTime(), nullable=True),
                    sa.Column('last_travel', sa.DateTime(), nullable=True),
                    sa.Column('last_gym_training', sa.DateTime(), nullable=True),
                    sa.Column('last_attack', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], name='fk_user_gang_id', use_alter=True),
                    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
                    sa.ForeignKeyConstraint(['referred_by_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('username')
                    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_gang_id'),
            ['gang_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_location_id'),
            ['location_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_referral_code'),
            ['referral_code'],
            unique=True)

    op.create_table('public_chat',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('message', sa.String(length=500), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )

    op.create_table('active_intel',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=False),
                    sa.Column('expires_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('asset',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('type', sa.String(length=50), nullable=False),
                    sa.Column('owner_id', sa.Integer(), nullable=True),
                    sa.Column('gang_id', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Integer(), nullable=True),
                    sa.Column('income', sa.Integer(), nullable=True),
                    sa.Column('maintenance_cost', sa.Integer(), nullable=True),
                    sa.Column('last_collected', sa.DateTime(), nullable=True),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('auction',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('item_type', sa.String(length=20), nullable=False),
                    sa.Column('item_id', sa.String(length=50), nullable=True),
                    sa.Column('seller_id', sa.Integer(), nullable=True),
                    sa.Column('start_price', sa.BigInteger(), nullable=False),
                    sa.Column('current_price', sa.BigInteger(), nullable=False),
                    sa.Column('min_bid_increment', sa.BigInteger(), nullable=True),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column('end_time', sa.DateTime(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('winner_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('bounty',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('placer_id', sa.Integer(), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['placer_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('casino_game',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('game_type', sa.String(length=32), nullable=False),
                    sa.Column('bet_amount', sa.BigInteger(), nullable=False),
                    sa.Column('state', sa.JSON(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('result', sa.String(length=20), nullable=True),
                    sa.Column('winnings', sa.BigInteger(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('casino_game', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_casino_game_status'),
            ['status'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_casino_game_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('combat_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('attacker_id', sa.Integer(), nullable=False),
                    sa.Column('defender_id', sa.Integer(), nullable=False),
                    sa.Column('winner_id', sa.Integer(), nullable=False),
                    sa.Column('money_stolen', sa.Integer(), nullable=True),
                    sa.Column('exp_gain', sa.Integer(), nullable=True),
                    sa.Column('is_attacker_anonymous', sa.Boolean(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['attacker_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['defender_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['winner_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('config_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('admin_id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=100), nullable=False),
                    sa.Column('old_value', sa.String(length=255), nullable=True),
                    sa.Column('new_value', sa.String(length=255), nullable=True),
                    sa.Column('reason', sa.String(length=255), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('config_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_config_log_admin_id'),
            ['admin_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_config_log_timestamp'),
            ['timestamp'],
            unique=False)

    op.create_table('crime_lobby',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('crime_id', sa.Integer(), nullable=False),
                    sa.Column('leader_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['crime_id'], ['organized_crime.id'], ),
                    sa.ForeignKeyConstraint(['leader_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_crime_lobby_leader_id'),
            ['leader_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_crime_lobby_status'),
            ['status'],
            unique=False)

    op.create_table('elite_title_seat',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title_key', sa.String(length=32), nullable=False),
                    sa.Column('seat_index', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('reserved_until', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('title_key', 'seat_index', name='uq_elite_title_seat_title_index')
                    )
    with op.batch_alter_table('elite_title_seat', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_elite_title_seat_title_key'),
            ['title_key'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_elite_title_seat_user_id'),
            ['user_id'],
            unique=True)

    op.create_table('factory_job',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('job_type', sa.String(length=32), nullable=False),
                    sa.Column('metal_used', sa.Integer(), nullable=True),
                    sa.Column('diamonds_used', sa.Integer(), nullable=True),
                    sa.Column('output_amount', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=16), nullable=True),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('ends_at', sa.DateTime(), nullable=False),
                    sa.Column('claimed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('factory_job', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_factory_job_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('farm_job',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('farm_type', sa.String(length=32), nullable=False),
                    sa.Column('output_item_id', sa.Integer(), nullable=True),
                    sa.Column('output_amount', sa.Integer(), nullable=True),
                    sa.Column('diamonds_used', sa.Integer(), nullable=True),
                    sa.Column('status', sa.String(length=16), nullable=True),
                    sa.Column('started_at', sa.DateTime(), nullable=True),
                    sa.Column('ends_at', sa.DateTime(), nullable=False),
                    sa.Column('claimed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['output_item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_farm_job_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('farm_supply_contract',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('location_id', sa.Integer(), nullable=False),
                    sa.Column('bonus_percent', sa.Float(), nullable=True),
                    sa.Column('status', sa.String(length=16), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('ends_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('farm_supply_contract', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_farm_supply_contract_location_id'),
            ['location_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_farm_supply_contract_status'),
            ['status'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_farm_supply_contract_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('forum_topic',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('is_pinned', sa.Boolean(), nullable=True),
                    sa.Column('is_locked', sa.Boolean(), nullable=True),
                    sa.Column('views', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('last_post_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id'], ['forum_category.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('futures_position',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=False),
                    sa.Column('position_type', sa.String(length=10), nullable=False),
                    sa.Column('entry_price', sa.Float(), nullable=False),
                    sa.Column('margin_amount', sa.Float(), nullable=False),
                    sa.Column('leverage', sa.Integer(), nullable=True),
                    sa.Column('quantity', sa.Float(), nullable=False),
                    sa.Column('liquidation_price', sa.Float(), nullable=False),
                    sa.Column('is_open', sa.Boolean(), nullable=True),
                    sa.Column('opened_at', sa.DateTime(), nullable=True),
                    sa.Column('closed_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['asset_id'], ['market_asset.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('game_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('admin_id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.String(length=128), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=True),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['admin_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_game_log_admin_id'),
            ['admin_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_game_log_timestamp'),
            ['timestamp'],
            unique=False)

    op.create_table('gang_invite',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('gang_invite', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_gang_invite_gang_id'),
            ['gang_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_gang_invite_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('gang_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('gang_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('action', sa.String(length=255), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['gang_id'], ['gang.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hostesses',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.Column('role', sa.String(length=32), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=True),
                    sa.Column('image', sa.String(length=128), nullable=True),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('dialogue_style', sa.String(length=32), nullable=True),
                    sa.Column('intro_message', sa.String(length=256), nullable=True),
                    sa.Column('buff_type', sa.String(length=32), nullable=True),
                    sa.Column('buff_value', sa.Float(), nullable=True),
                    sa.Column('system_prompt', sa.Text(), nullable=True),
                    sa.Column('training_examples', sa.Text(), nullable=True),
                    sa.Column('video', sa.String(length=128), nullable=True),
                    sa.Column('video_prompt', sa.Text(), nullable=True),
                    sa.Column('voice_config', sa.Text(), nullable=True),
                    sa.Column('personality_config', sa.Text(), nullable=True),
                    sa.Column('appearance_config', sa.Text(), nullable=True),
                    sa.Column('knowledge_base', sa.Text(), nullable=True),
                    sa.Column('is_avatar_active', sa.Boolean(), nullable=True),
                    sa.Column('self_learning_enabled', sa.Boolean(), nullable=True),
                    sa.Column('memory_enabled', sa.Boolean(), nullable=True),
                    sa.Column('last_trained_at', sa.DateTime(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('exp', sa.Integer(), nullable=True),
                    sa.Column('charm', sa.Integer(), nullable=True),
                    sa.Column('intelligence', sa.Integer(), nullable=True),
                    sa.Column('combat_skill', sa.Integer(), nullable=True),
                    sa.Column('loyalty', sa.Integer(), nullable=True),
                    sa.Column('special_move_cooldown', sa.DateTime(), nullable=True),
                    sa.Column('current_player_id', sa.Integer(), nullable=True),
                    sa.Column('min_rank', sa.Integer(), nullable=True),
                    sa.Column('is_public', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['current_player_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('current_player_id')
                    )
    op.create_table('investigation_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('investigator_id', sa.Integer(), nullable=False),
                    sa.Column('target_id', sa.Integer(), nullable=False),
                    sa.Column('success', sa.Boolean(), nullable=True),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['investigator_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['target_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('investigation_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_investigation_log_investigator_id'),
            ['investigator_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_investigation_log_target_id'),
            ['target_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_investigation_log_timestamp'),
            ['timestamp'],
            unique=False)

    op.create_table('message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('sender_id', sa.Integer(), nullable=False),
                    sa.Column('receiver_id', sa.Integer(), nullable=False),
                    sa.Column('subject', sa.String(length=100), nullable=False),
                    sa.Column('body', sa.Text(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('deleted_by_sender', sa.Boolean(), nullable=True),
                    sa.Column('deleted_by_receiver', sa.Boolean(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('delivery_time', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(
            'idx_message_receiver_read', [
                'receiver_id', 'is_read'], unique=False)

    op.create_table('money_sink_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('sink_type', sa.String(length=50), nullable=False),
                    sa.Column('amount', sa.Integer(), nullable=False),
                    sa.Column('details', sa.String(length=255), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('money_sink_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_money_sink_log_timestamp'),
            ['timestamp'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_money_sink_log_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('notification',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('message', sa.Text(), nullable=False),
                    sa.Column('is_read', sa.Boolean(), nullable=True),
                    sa.Column('type', sa.String(length=50), nullable=True),
                    sa.Column('link', sa.String(length=255), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_notification_created_at'),
            ['created_at'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_notification_is_read'),
            ['is_read'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_notification_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('payment_transaction',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('amount_usd', sa.Float(), nullable=False),
                    sa.Column('diamonds_amount', sa.Integer(), nullable=False),
                    sa.Column('transaction_id', sa.String(length=100), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('payment_method', sa.String(length=50), nullable=True),
                    sa.Column('payment_proof', sa.Text(), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('transaction_id')
                    )
    op.create_table('race',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('creator_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('bet_amount', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('referral',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('referrer_id', sa.Integer(), nullable=False),
                    sa.Column('referred_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['referred_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('resurrection_request',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('admin_note', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('spot_order',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=False),
                    sa.Column('order_type', sa.String(length=10), nullable=False),
                    sa.Column('price', sa.Float(), nullable=False),
                    sa.Column('quantity', sa.Float(), nullable=False),
                    sa.Column('filled_quantity', sa.Float(), nullable=True),
                    sa.Column('status', sa.String(length=20), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['asset_id'], ['market_asset.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.create_index(
            'idx_spot_order_asset_status', [
                'asset_id', 'status'], unique=False)
        batch_op.create_index(
            'idx_spot_order_user_status', [
                'user_id', 'status'], unique=False)

    op.create_table('user_achievement',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('achievement_id', sa.Integer(), nullable=False),
                    sa.Column('unlocked_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['achievement_id'], ['achievement.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_achievement_achievement_id'),
            ['achievement_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_achievement_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('user_crime_cooldown',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('crime_id', sa.Integer(), nullable=False),
                    sa.Column('cooldown_until', sa.DateTime(), nullable=False),
                    sa.Column('daily_count', sa.Integer(), nullable=True),
                    sa.Column('last_reset_date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['crime_id'], ['crime.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_organized_crime_cooldown',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('crime_id', sa.Integer(), nullable=False),
                    sa.Column('cooldown_until', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['crime_id'], ['organized_crime.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_daily_task',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('task_id', sa.Integer(), nullable=False),
                    sa.Column('progress', sa.Integer(), nullable=True),
                    sa.Column('is_completed', sa.Boolean(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(['task_id'], ['daily_task.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_facility',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('facility_key', sa.String(length=32), nullable=False),
                    sa.Column('level', sa.Integer(), nullable=True),
                    sa.Column('last_perk_at', sa.DateTime(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_facility', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_facility_facility_key'),
            ['facility_key'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_facility_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('user_investment',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('asset_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Float(), nullable=True),
                    sa.Column('average_buy_price', sa.Float(), nullable=True),
                    sa.ForeignKeyConstraint(['asset_id'], ['market_asset.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_item',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('item_id', sa.Integer(), nullable=False),
                    sa.Column('quantity', sa.Integer(), nullable=True),
                    sa.Column('is_equipped', sa.Boolean(), nullable=True),
                    sa.Column('condition', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.create_index(
            'idx_user_item_user_equipped', [
                'user_id', 'is_equipped'], unique=False)

    op.create_table('user_log',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('action', sa.String(length=50), nullable=False),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('result', sa.String(length=20), nullable=True),
                    sa.Column('before_state', sa.JSON(), nullable=True),
                    sa.Column('after_state', sa.JSON(), nullable=True),
                    sa.Column('ip_address', sa.String(length=45), nullable=True),
                    sa.Column('user_agent', sa.String(length=255), nullable=True),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_user_log_action'),
            ['action'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_log_timestamp'),
            ['timestamp'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_user_log_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('user_progress',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('rank_points', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_vehicle',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('condition', sa.Integer(), nullable=True),
                    sa.Column('engine_level', sa.Integer(), nullable=True),
                    sa.Column('tires_level', sa.Integer(), nullable=True),
                    sa.Column('armor_level', sa.Integer(), nullable=True),
                    sa.Column('repair_until', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('weekly_winner',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('week_number', sa.Integer(), nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('amount_won', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('auction_bid',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('auction_id', sa.Integer(), nullable=False),
                    sa.Column('bidder_id', sa.Integer(), nullable=False),
                    sa.Column('amount', sa.BigInteger(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(), nullable=True),
                    sa.Column('is_refunded', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['auction_id'], ['auction.id'], ),
                    sa.ForeignKeyConstraint(['bidder_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('auction_bid', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_auction_bid_auction_id'),
            ['auction_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_auction_bid_bidder_id'),
            ['bidder_id'],
            unique=False)

    op.create_table('forum_post',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('topic_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['topic_id'], ['forum_topic.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('hostess_chat_messages',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hostess_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('role', sa.String(length=16), nullable=False),
                    sa.Column('content', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['hostess_id'], ['hostesses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('hostess_chat_messages', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_hostess_chat_messages_hostess_id'),
            ['hostess_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_hostess_chat_messages_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('hostess_knowledge',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hostess_id', sa.Integer(), nullable=True),
                    sa.Column('question', sa.Text(), nullable=False),
                    sa.Column('answer', sa.Text(), nullable=False),
                    sa.Column('category', sa.String(length=64), nullable=True),
                    sa.Column('keywords', sa.Text(), nullable=True),
                    sa.Column('language', sa.String(length=10), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['hostess_id'], ['hostesses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('hostess_knowledge', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_hostess_knowledge_category'),
            ['category'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_hostess_knowledge_language'),
            ['language'],
            unique=False)

    op.create_table('hostess_memories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('hostess_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=64), nullable=False),
                    sa.Column('value', sa.Text(), nullable=False),
                    sa.Column('importance', sa.Integer(), nullable=True),
                    sa.Column('source', sa.String(length=16), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=True),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['hostess_id'], ['hostesses.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('hostess_memories', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_hostess_memories_hostess_id'),
            ['hostess_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_hostess_memories_key'),
            ['key'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_hostess_memories_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('lobby_participant',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('lobby_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('role_name', sa.String(length=50), nullable=True),
                    sa.Column('is_ready', sa.Boolean(), nullable=True),
                    sa.Column('joined_at', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['lobby_id'], ['crime_lobby.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('lobby_participant', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_lobby_participant_lobby_id'),
            ['lobby_id'],
            unique=False)
        batch_op.create_index(
            batch_op.f('ix_lobby_participant_user_id'),
            ['user_id'],
            unique=False)

    op.create_table('race_participant',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('race_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('user_vehicle_id', sa.Integer(), nullable=False),
                    sa.Column('score', sa.Float(), nullable=True),
                    sa.Column('rank', sa.Integer(), nullable=True),
                    sa.Column('reward', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['race_id'], ['race.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.ForeignKeyConstraint(['user_vehicle_id'], ['user_vehicle.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('race_participant')
    with op.batch_alter_table('lobby_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lobby_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_lobby_participant_lobby_id'))

    op.drop_table('lobby_participant')
    with op.batch_alter_table('hostess_memories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostess_memories_user_id'))
        batch_op.drop_index(batch_op.f('ix_hostess_memories_key'))
        batch_op.drop_index(batch_op.f('ix_hostess_memories_hostess_id'))

    op.drop_table('hostess_memories')
    with op.batch_alter_table('hostess_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostess_knowledge_language'))
        batch_op.drop_index(batch_op.f('ix_hostess_knowledge_category'))

    op.drop_table('hostess_knowledge')
    with op.batch_alter_table('hostess_chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostess_chat_messages_user_id'))
        batch_op.drop_index(batch_op.f('ix_hostess_chat_messages_hostess_id'))

    op.drop_table('hostess_chat_messages')
    op.drop_table('forum_post')
    with op.batch_alter_table('auction_bid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_bid_bidder_id'))
        batch_op.drop_index(batch_op.f('ix_auction_bid_auction_id'))

    op.drop_table('auction_bid')
    op.drop_table('weekly_winner')
    op.drop_table('user_vehicle')
    op.drop_table('user_progress')
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_log_action'))

    op.drop_table('user_log')
    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.drop_index('idx_user_item_user_equipped')

    op.drop_table('user_item')
    op.drop_table('user_investment')
    with op.batch_alter_table('user_facility', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_facility_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_facility_facility_key'))

    op.drop_table('user_facility')
    op.drop_table('user_daily_task')
    op.drop_table('user_organized_crime_cooldown')
    op.drop_table('user_crime_cooldown')
    with op.batch_alter_table('user_achievement', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_achievement_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_achievement_achievement_id'))

    op.drop_table('user_achievement')
    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.drop_index('idx_spot_order_user_status')
        batch_op.drop_index('idx_spot_order_asset_status')

    op.drop_table('spot_order')
    op.drop_table('resurrection_request')
    op.drop_table('referral')
    op.drop_table('race')
    op.drop_table('payment_transaction')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))
        batch_op.drop_index(batch_op.f('ix_notification_created_at'))

    op.drop_table('notification')
    with op.batch_alter_table('money_sink_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_money_sink_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_money_sink_log_timestamp'))

    op.drop_table('money_sink_log')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index('idx_message_receiver_read')

    op.drop_table('message')
    with op.batch_alter_table('investigation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_investigation_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_investigation_log_investigator_id'))

    op.drop_table('investigation_log')
    op.drop_table('hostesses')
    op.drop_table('gang_log')
    with op.batch_alter_table('gang_invite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_invite_user_id'))
        batch_op.drop_index(batch_op.f('ix_gang_invite_gang_id'))

    op.drop_table('gang_invite')
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_game_log_admin_id'))

    op.drop_table('game_log')
    op.drop_table('futures_position')
    op.drop_table('forum_topic')
    with op.batch_alter_table('farm_supply_contract', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_supply_contract_user_id'))
        batch_op.drop_index(batch_op.f('ix_farm_supply_contract_status'))
        batch_op.drop_index(batch_op.f('ix_farm_supply_contract_location_id'))

    op.drop_table('farm_supply_contract')
    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_job_user_id'))

    op.drop_table('farm_job')
    with op.batch_alter_table('factory_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_factory_job_user_id'))

    op.drop_table('factory_job')
    with op.batch_alter_table('elite_title_seat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_elite_title_seat_user_id'))
        batch_op.drop_index(batch_op.f('ix_elite_title_seat_title_key'))

    op.drop_table('elite_title_seat')
    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_lobby_status'))
        batch_op.drop_index(batch_op.f('ix_crime_lobby_leader_id'))

    op.drop_table('crime_lobby')
    with op.batch_alter_table('config_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_config_log_admin_id'))

    op.drop_table('config_log')
    op.drop_table('combat_log')
    with op.batch_alter_table('casino_game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_casino_game_user_id'))
        batch_op.drop_index(batch_op.f('ix_casino_game_status'))

    op.drop_table('casino_game')
    op.drop_table('bounty')
    op.drop_table('auction')
    op.drop_table('asset')
    op.drop_table('public_chat')
    op.drop_table('active_intel')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_referral_code'))
        batch_op.drop_index(batch_op.f('ix_user_location_id'))
        batch_op.drop_index(batch_op.f('ix_user_gang_id'))

    op.drop_table('user')
    op.drop_table('gang_war')
    with op.batch_alter_table('gang_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_item_gang_id'))

    op.drop_table('gang_item')
    op.drop_table('gang_alliance')
    op.drop_table('crime')
    op.drop_table('video_scenarios')
    op.drop_table('vehicle')
    op.drop_table('user_rank')
    op.drop_table('system_config')
    op.drop_table('security_log')
    op.drop_table('organized_crime')
    op.drop_table('market_asset')
    op.drop_table('location')
    op.drop_table('learning_logs')
    op.drop_table('item')
    op.drop_table('heist_history')
    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_leader_id'))

    op.drop_table('gang')
    op.drop_table('forum_category')
    with op.batch_alter_table('economy_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economy_snapshot_date'))

    op.drop_table('economy_snapshot')
    op.drop_table('daily_task')
    op.drop_table('announcement')
    op.drop_table('achievement')
    # ### end Alembic commands ###
