"""add gender and birthdate to user

Revision ID: 5a4b3c2d1e0f
Revises: 14db83577c98
Create Date: 2026-01-13 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a4b3c2d1e0f'
down_revision = '14db83577c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'gender',
                sa.String(
                    length=10),
                nullable=True,
                server_default='male'))
        batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))

    # Remove server default after adding (optional, but cleaner)
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('birthdate')
        batch_op.drop_column('gender')
    # ### end Alembic commands ###
