"""improve_chat_schema

Revision ID: 7f8e9d0a1b2c
Revises: 2c1c9b9e5e10
Create Date: 2026-01-13 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f8e9d0a1b2c'
down_revision = '2c1c9b9e5e10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'chat_muted_until',
                sa.DateTime(),
                nullable=True))
    op.create_index('idx_public_chat_created_at', 'public_chat', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_public_chat_created_at', table_name='public_chat')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('chat_muted_until')
    # ### end Alembic commands ###
