"""optimize_market_and_gameplay_indexes

Revision ID: 9124fe2bf48a
Revises: 380a7cb143ee
Create Date: 2026-01-08 22:39:25.274169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9124fe2bf48a'
down_revision = '380a7cb143ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('active_intel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_intel_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_intel_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_asset_gang_id'), ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_asset_owner_id'), ['owner_id'], unique=False)

    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_end_time'), ['end_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_seller_id'), ['seller_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_auction_winner_id'), ['winner_id'], unique=False)

    with op.batch_alter_table('auction_bid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auction_bid_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('bounty', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bounty_placer_id'), ['placer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bounty_target_id'), ['target_id'], unique=False)

    with op.batch_alter_table('combat_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_combat_log_attacker_id'), ['attacker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_log_defender_id'), ['defender_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_log_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_combat_log_winner_id'), ['winner_id'], unique=False)

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_cooldown'), ['cooldown'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_min_level'), ['min_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_reward_item_id'), ['reward_item_id'], unique=False)

    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_lobby_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_lobby_crime_id'), ['crime_id'], unique=False)
        batch_op.create_index('idx_crime_lobby_status_created', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_farm_job_output_item_id'), ['output_item_id'], unique=False)

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_forum_post_topic_id'), ['topic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_forum_post_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('futures_position', schema=None) as batch_op:
        batch_op.create_index('idx_futures_liq_check', ['asset_id', 'is_open', 'position_type', 'liquidation_price'], unique=False)
        batch_op.create_index('idx_futures_position_user_open', ['user_id', 'is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_closed_at'), ['closed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_is_open'), ['is_open'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_liquidation_price'), ['liquidation_price'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_futures_position_position_type'), ['position_type'], unique=False)

    with op.batch_alter_table('game_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_chat_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_chat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_players_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_game_players_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_underboss_id'), ['underboss_id'], unique=False)

    with op.batch_alter_table('gang_alliance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_alliance_gang1_id'), ['gang1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_alliance_gang2_id'), ['gang2_id'], unique=False)

    with op.batch_alter_table('gang_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_item_gang_id'), ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_item_item_id'), ['item_id'], unique=False)

    with op.batch_alter_table('gang_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_log_gang_id'), ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('gang_war', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gang_war_gang1_id'), ['gang1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_war_gang2_id'), ['gang2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gang_war_winner_id'), ['winner_id'], unique=False)

    with op.batch_alter_table('heist_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_heist_history_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('hostess_chat_messages', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('hostess_knowledge', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hostess_knowledge_hostess_id'), ['hostess_id'], unique=False)

    with op.batch_alter_table('hostess_memories', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('market_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_asset_asset_type'), ['asset_type'], unique=False)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('organized_crime', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organized_crime_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_organized_crime_min_gang_level'), ['min_gang_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_organized_crime_min_level'), ['min_level'], unique=False)

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_transaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('public_chat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_public_chat_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_creator_id'), ['creator_id'], unique=False)

    with op.batch_alter_table('race_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_participant_race_id'), ['race_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_participant_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_participant_user_vehicle_id'), ['user_vehicle_id'], unique=False)

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_referral_referred_id'), ['referred_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_referral_referrer_id'), ['referrer_id'], unique=False)

    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.create_index('idx_spot_order_exec_buy', ['asset_id', 'status', 'order_type', 'price'], unique=False)
        batch_op.create_index(batch_op.f('ix_spot_order_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_active_hostess_id'), ['active_hostess_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_heat_updated_at'), ['heat_updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_crime'), ['last_crime'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_daily_reward'), ['last_daily_reward'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_travel'), ['last_travel'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_referred_by_id'), ['referred_by_id'], unique=False)
        batch_op.create_foreign_key(None, 'hostesses', ['active_hostess_id'], ['id'])

    with op.batch_alter_table('user_crime_cooldown', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_crime_cooldown_cooldown_until'), ['cooldown_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_crime_cooldown_crime_id'), ['crime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_crime_cooldown_user_id'), ['user_id'], unique=False)
        batch_op.create_index('idx_user_crime_cooldown_user_crime', ['user_id', 'crime_id'], unique=False)

    with op.batch_alter_table('user_daily_task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_daily_task_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_daily_task_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_investment', schema=None) as batch_op:
        batch_op.create_index('idx_user_investment_user_asset', ['user_id', 'asset_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_investment_asset_id'), ['asset_id'], unique=False)

    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_item_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_item_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_organized_crime_cooldown', schema=None) as batch_op:
        batch_op.create_index('idx_user_org_crime_cooldown_user_crime', ['user_id', 'crime_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_organized_crime_cooldown_cooldown_until'), ['cooldown_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_organized_crime_cooldown_crime_id'), ['crime_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_organized_crime_cooldown_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_progress_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vehicle_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vehicle_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('weekly_winner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_winner_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('weekly_winner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_winner_user_id'))

    with op.batch_alter_table('user_vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vehicle_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_user_vehicle_user_id'))

    with op.batch_alter_table('user_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_progress_user_id'))

    with op.batch_alter_table('user_organized_crime_cooldown', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_organized_crime_cooldown_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_organized_crime_cooldown_crime_id'))
        batch_op.drop_index(batch_op.f('ix_user_organized_crime_cooldown_cooldown_until'))
        batch_op.drop_index('idx_user_org_crime_cooldown_user_crime')

    with op.batch_alter_table('user_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_item_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_item_item_id'))

    with op.batch_alter_table('user_investment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_investment_asset_id'))
        batch_op.drop_index('idx_user_investment_user_asset')

    with op.batch_alter_table('user_daily_task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_daily_task_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_daily_task_task_id'))

    with op.batch_alter_table('user_crime_cooldown', schema=None) as batch_op:
        batch_op.drop_index('idx_user_crime_cooldown_user_crime')
        batch_op.drop_index(batch_op.f('ix_user_crime_cooldown_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_crime_cooldown_crime_id'))
        batch_op.drop_index(batch_op.f('ix_user_crime_cooldown_cooldown_until'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_user_referred_by_id'))
        batch_op.drop_index(batch_op.f('ix_user_last_travel'))
        batch_op.drop_index(batch_op.f('ix_user_last_daily_reward'))
        batch_op.drop_index(batch_op.f('ix_user_last_crime'))
        batch_op.drop_index(batch_op.f('ix_user_heat_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index(batch_op.f('ix_user_active_hostess_id'))

    with op.batch_alter_table('spot_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spot_order_created_at'))
        batch_op.drop_index('idx_spot_order_exec_buy')

    with op.batch_alter_table('referral', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_referral_referrer_id'))
        batch_op.drop_index(batch_op.f('ix_referral_referred_id'))

    with op.batch_alter_table('race_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_participant_user_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_race_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_race_participant_race_id'))

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_creator_id'))

    with op.batch_alter_table('public_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_public_chat_user_id'))

    with op.batch_alter_table('payment_transaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_transaction_user_id'))

    with op.batch_alter_table('organized_crime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organized_crime_min_level'))
        batch_op.drop_index(batch_op.f('ix_organized_crime_min_gang_level'))
        batch_op.drop_index(batch_op.f('ix_organized_crime_is_active'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_sender_id'))

    with op.batch_alter_table('market_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_asset_asset_type'))

    with op.batch_alter_table('hostess_memories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hostess_knowledge', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hostess_knowledge_hostess_id'))

    with op.batch_alter_table('hostess_chat_messages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('heist_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_heist_history_created_at'))

    with op.batch_alter_table('gang_war', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_war_winner_id'))
        batch_op.drop_index(batch_op.f('ix_gang_war_gang2_id'))
        batch_op.drop_index(batch_op.f('ix_gang_war_gang1_id'))

    with op.batch_alter_table('gang_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_gang_log_gang_id'))

    with op.batch_alter_table('gang_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_item_item_id'))
        batch_op.drop_index(batch_op.f('ix_gang_item_gang_id'))

    with op.batch_alter_table('gang_alliance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_alliance_gang2_id'))
        batch_op.drop_index(batch_op.f('ix_gang_alliance_gang1_id'))

    with op.batch_alter_table('gang', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gang_underboss_id'))

    with op.batch_alter_table('game_players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_players_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_players_room_id'))

    with op.batch_alter_table('game_chat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_chat_user_id'))
        batch_op.drop_index(batch_op.f('ix_game_chat_room_id'))

    with op.batch_alter_table('futures_position', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_futures_position_opened_at'))
        batch_op.drop_index(batch_op.f('ix_futures_position_liquidation_price'))
        batch_op.drop_index(batch_op.f('ix_futures_position_is_open'))
        batch_op.drop_index(batch_op.f('ix_futures_position_closed_at'))
        batch_op.drop_index(batch_op.f('ix_futures_position_asset_id'))
        batch_op.drop_index('idx_futures_position_user_open')
        batch_op.drop_index('idx_futures_liq_check')
        batch_op.drop_index(batch_op.f('ix_futures_position_position_type'))

    with op.batch_alter_table('forum_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_forum_post_user_id'))
        batch_op.drop_index(batch_op.f('ix_forum_post_topic_id'))

    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_farm_job_output_item_id'))

    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_lobby_crime_id'))
        batch_op.drop_index(batch_op.f('ix_crime_lobby_created_at'))
        batch_op.drop_index('idx_crime_lobby_status_created')

    with op.batch_alter_table('crime', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_reward_item_id'))
        batch_op.drop_index(batch_op.f('ix_crime_min_level'))
        batch_op.drop_index(batch_op.f('ix_crime_is_active'))
        batch_op.drop_index(batch_op.f('ix_crime_cooldown'))

    with op.batch_alter_table('combat_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_combat_log_winner_id'))
        batch_op.drop_index(batch_op.f('ix_combat_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_combat_log_defender_id'))
        batch_op.drop_index(batch_op.f('ix_combat_log_attacker_id'))

    with op.batch_alter_table('bounty', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bounty_target_id'))
        batch_op.drop_index(batch_op.f('ix_bounty_placer_id'))

    with op.batch_alter_table('auction_bid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_bid_timestamp'))

    with op.batch_alter_table('auction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auction_winner_id'))
        batch_op.drop_index(batch_op.f('ix_auction_status'))
        batch_op.drop_index(batch_op.f('ix_auction_seller_id'))
        batch_op.drop_index(batch_op.f('ix_auction_end_time'))

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_asset_owner_id'))
        batch_op.drop_index(batch_op.f('ix_asset_gang_id'))

    with op.batch_alter_table('active_intel', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_intel_user_id'))
        batch_op.drop_index(batch_op.f('ix_active_intel_target_id'))

    # ### end Alembic commands ###
