"""check_pending_changes

Revision ID: ad5bbcb68d30
Revises: e8d816580abd
Create Date: 2025-12-24 22:16:55.337545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad5bbcb68d30'
down_revision = 'e8d816580abd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('engine_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tires_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('armor_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_vehicle', schema=None) as batch_op:
        batch_op.drop_column('armor_level')
        batch_op.drop_column('tires_level')
        batch_op.drop_column('engine_level')

    # ### end Alembic commands ###
