"""add daily bullets purchased

Revision ID: b3d4e5f6g7h8
Revises: b2c3d4e5f6g7
Create Date: 2026-01-01 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3d4e5f6g7h8'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('daily_bullets_purchased', sa.Integer(), nullable=True, server_default='0'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'daily_bullets_purchased')
    # ### end Alembic commands ###
