"""Add knowledge_base to Hostess and greeter role

Revision ID: bfefe2677f46
Revises: d28193bacad3
Create Date: 2025-12-25 14:50:20.685306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfefe2677f46'
down_revision = 'd28193bacad3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge_base', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostesses', schema=None) as batch_op:
        batch_op.drop_column('knowledge_base')

    # ### end Alembic commands ###
