"""add voice and personality config

Revision ID: d28193bacad3
Revises: ad5bbcb68d30
Create Date: 2025-12-25 14:32:46.737502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd28193bacad3'
down_revision = 'ad5bbcb68d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voice_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('personality_config', sa.Text(), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hostesses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('personality_config')
        batch_op.drop_column('voice_config')

    # ### end Alembic commands ###
