"""add_version_column

Revision ID: e2adb7665786
Revises: 8c4f1a2b3d45
Create Date: 2025-12-31 22:51:20.149969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e2adb7665786'
down_revision = '8c4f1a2b3d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_task_is_active')
        batch_op.drop_index('ix_daily_task_min_level')
        batch_op.drop_index('ix_daily_task_target_type')

    with op.batch_alter_table('factory_job', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('claimed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_factory_job_status')

    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('claimed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_index('ix_farm_job_status')

    with op.batch_alter_table('farm_supply_contract', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ends_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('user_daily_task', schema=None) as batch_op:
        batch_op.drop_index('ix_user_daily_task_date')
        batch_op.drop_index('ix_user_daily_task_is_completed')
        batch_op.drop_index('ix_user_daily_task_user_id')

    with op.batch_alter_table('user_facility', schema=None) as batch_op:
        batch_op.alter_column('last_perk_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('uq_user_facility_user_key', type_='unique')

    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('before_state', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after_state', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_log', schema=None) as batch_op:
        batch_op.drop_column('after_state')
        batch_op.drop_column('before_state')

    with op.batch_alter_table('user_facility', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_facility_user_key', ['user_id', 'facility_key'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('last_perk_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('user_daily_task', schema=None) as batch_op:
        batch_op.create_index('ix_user_daily_task_user_id', ['user_id'], unique=False)
        batch_op.create_index('ix_user_daily_task_is_completed', ['is_completed'], unique=False)
        batch_op.create_index('ix_user_daily_task_date', ['date'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('version')

    with op.batch_alter_table('farm_supply_contract', schema=None) as batch_op:
        batch_op.alter_column('ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('farm_job', schema=None) as batch_op:
        batch_op.create_index('ix_farm_job_status', ['status'], unique=False)
        batch_op.alter_column('claimed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('factory_job', schema=None) as batch_op:
        batch_op.create_index('ix_factory_job_status', ['status'], unique=False)
        batch_op.alter_column('claimed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('ends_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('daily_task', schema=None) as batch_op:
        batch_op.create_index('ix_daily_task_target_type', ['target_type'], unique=False)
        batch_op.create_index('ix_daily_task_min_level', ['min_level'], unique=False)
        batch_op.create_index('ix_daily_task_is_active', ['is_active'], unique=False)

    # ### end Alembic commands ###
