"""Add indexes for performance optimization

Revision ID: f3437c161fa2
Revises: 
Create Date: 2025-12-24 12:56:55.455692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3437c161fa2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crime_lobby_leader_id'), ['leader_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crime_lobby_status'), ['status'], unique=False)

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('investigation_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_investigation_log_investigator_id'), ['investigator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_log_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_investigation_log_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('lobby_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lobby_participant_lobby_id'), ['lobby_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lobby_participant_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_gang_id'), ['gang_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_location_id'), ['location_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_location_id'))
        batch_op.drop_index(batch_op.f('ix_user_gang_id'))

    with op.batch_alter_table('lobby_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lobby_participant_user_id'))
        batch_op.drop_index(batch_op.f('ix_lobby_participant_lobby_id'))

    with op.batch_alter_table('investigation_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_investigation_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_investigation_log_target_id'))
        batch_op.drop_index(batch_op.f('ix_investigation_log_investigator_id'))

    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_log_timestamp'))

    with op.batch_alter_table('crime_lobby', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crime_lobby_status'))
        batch_op.drop_index(batch_op.f('ix_crime_lobby_leader_id'))

    # ### end Alembic commands ###
