import os
import re

PO_FILE = 'translations/en/LC_MESSAGES/messages.po'

COMMON_TRANSLATIONS = {
    "ID": "المعرف",
    "Name": "الاسم",
    "Role": "الدور",
    "Delete": "حذف",
    "Edit": "تعديل",
    "View": "عرض",
    "Candles": "شموع",
    "SMA 20": "متوسط بسيط 20",
    "EMA 50": "متوسط آسي 50",
    "BB": "بولنجر",
    "System": "النظام",
    "Type": "النوع",
    "Status": "الحالة",
    "Date": "التاريخ",
    "Action": "إجراء",
    "Actions": "إجراءات",
    "Level": "المستوى",
    "Experience": "الخبرة",
    "Money": "المال",
    "Bullets": "الرصاص",
    "Health": "الصحة",
    "Energy": "الطاقة",
    "Gang": "العصابة",
    "Username": "اسم المستخدم",
    "Password": "كلمة المرور",
    "Email": "البريد الإلكتروني",
    "Login": "دخول",
    "Register": "تسجيل",
    "Logout": "خروج",
    "Cancel": "إلغاء",
    "Save": "حفظ",
    "Update": "تحديث",
    "Create": "إنشاء",
    "Search": "بحث",
    "Filter": "تصفية",
    "Reset": "إعادة تعيين",
    "Yes": "نعم",
    "No": "لا",
    "Close": "إغلاق",
    "Back": "عودة",
    "Next": "التالي",
    "Previous": "السابق",
    "Home": "الرئيسية",
    "Dashboard": "لوحة التحكم",
    "Profile": "الملف الشخصي",
    "Settings": "الإعدادات",
    "Speaker": "المتحدث",
    "Text": "النص",
    "Emotion": "المشاعر",
    "Intro message will appear here...": "رسالة المقدمة ستظهر هنا...",
    "No Image": "لا توجد صورة",
    "FPS": "إطار في الثانية",
    "Key (e.g. xp_multiplier)": "المفتاح (مثل xp_multiplier)",
    "Value (e.g. 1.5)": "القيمة (مثل 1.5)",
    "PS,JO,EG (comma separated ISO codes)": "PS,JO,EG (رموز الدول مفصولة بفواصل)",
    "Active": "نشط",
    "Inactive": "غير نشط",
    "Pending": "قيد الانتظار",
    "Approved": "مقبول",
    "Rejected": "مرفوض",
    "Banned": "محظور",
    "Admin": "مدير",
    "User": "مستخدم",
    "Guest": "زائر",
    "Unknown": "غير معروف",
    "Success": "نجاح",
    "Error": "خطأ",
    "Warning": "تحذير",
    "Info": "معلومات",
    "Confirm": "تأكيد",
    "Price": "السعر",
    "Quantity": "الكمية",
    "Total": "المجموع",
    "Description": "الوصف",
    "Image": "الصورة",
    "Title": "العنوان",
    "Content": "المحتوى",
    "Category": "التصنيف",
    "Time": "الوقت",
    "Day": "اليوم",
    "Month": "الشهر",
    "Year": "السنة",
    "Hour": "ساعة",
    "Minute": "دقيقة",
    "Second": "ثانية",
    "All": "الكل",
    "None": "لا شيء",
    "Select": "اختر",
    "Options": "خيارات",
    "Result": "النتيجة",
    "Score": "النقاط",
    "Rank": "الرتبة",
    "Winner": "الفائز",
    "Loser": "الخاسر",
    "Game": "لعبة",
    "Player": "لاعب",
    "Team": "فريق",
    "Group": "مجموعة",
    "Chat": "دردشة",
    "Message": "رسالة",
    "Send": "إرسال",
    "Receive": "استلام",
    "Flirt": "دلع",
    "Shy": "خجل",
    "Dom": "سيطرة",
    "Style": "ستايل",
    "Video Configuration": "إعدادات الفيديو",
    "Browser (Free)": "متصفح (مجاني)",
    "ElevenLabs": "ElevenLabs",
    "OpenAI TTS": "OpenAI TTS",
    "Casual Chic": "كاجوال شيك",
    "Elegant Evening": "سهرة فاخرة",
    "Sexy Lingerie": "لانجري مثير",
    "Street Fighter": "حرب شوارع",
    "Cyberpunk": "سايبر بانك",
    "Video Prompt Builder": "منشئ سيناريو الفيديو",
    "Constraints": "قيود",
    "Shots": "لقطات",
    "Music Mood": "مزاج الموسيقى",
    "Visual Style": "نمط بصري",
    "Lighting": "الإضاءة",
    "Color Grade": "تصحيح الألوان",
    "Avoid": "تجنب",
    "Physics": "فيزياء",
    "Negative Prompts": "تلقين سلبي",
    "Buy": "شراء",
    "Sell": "بيع",
    "Trade": "تداول",
    "Market": "السوق",
    "Bank": "البنك",
    "Casino": "الكازينو",
    "Jail": "السجن",
    "Hospital": "المستشفى",
    "Gym": "النادي الرياضي",
    "School": "المدرسة",
    "University": "الجامعة",
    "Work": "العمل",
    "Job": "وظيفة",
    "Crime": "جريمة",
    "Crimes": "جرائم",
    "Mission": "مهمة",
    "Missions": "مهام",
    "Reward": "مكافأة",
    "Penalty": "غرامة",
    "Tax": "ضريبة",
    "Fees": "رسوم",
    "Balance": "الرصيد",
    "Deposit": "إيداع",
    "Withdraw": "سحب",
    "Transfer": "تحويل",
    "History": "السجل",
    "Logs": "السجلات",
    "Stats": "الإحصائيات",
    "Skills": "المهارات",
    "Items": "العناصر",
    "Inventory": "المخزون",
    "Shop": "المتجر",
    "Equip": "تجهيز",
    "Unequip": "إلغاء التجهيز",
    "Use": "استخدام",
    "Drop": "إلقاء",
    "Give": "إعطاء",
    "Take": "أخذ",
    "Attack": "هجوم",
    "Defend": "دفاع",
    "Run": "هرب",
    "Escape": "هروب",
    "Win": "فوز",
    "Lose": "خسارة",
    "Draw": "تعادل",
    "Kill": "قتل",
    "Die": "موت",
    "Revive": "إنعاش",
    "Heal": "علاج",
    "Repair": "إصلاح",
    "Upgrade": "ترقية",
    "Downgrade": "تخفيض",
    "Install": "تثبيت",
    "Uninstall": "إلغاء التثبيت",
    "Open": "فتح",
    "Closed": "مغلق",
    "Locked": "مقفول",
    "Unlocked": "مفتوح",
    "Private": "خاص",
    "Public": "عام",
    "Global": "عالمي",
    "Local": "محلي",
    "Server": "الخادم",
    "Client": "العميل",
    "Connection": "الاتصال",
    "Online": "متصل",
    "Offline": "غير متصل",
    "Busy": "مشغول",
    "Available": "متاح",
    "Unavailable": "غير متاح",
    "Forbidden": "ممنوع",
    "Allowed": "مسموح",
    "Required": "مطلوب",
    "Optional": "اختياري",
    "Default": "افتراضي",
    "Custom": "مخصص",
    "New": "جديد",
    "Old": "قديم",
    "Recent": "حديث",
    "Popular": "شائع",
    "Favorite": "مفضل",
    "Favorites": "المفضلة",
    "Like": "إعجاب",
    "Dislike": "لم يعجبني",
    "Comment": "تعليق",
    "Share": "مشاركة",
    "Report": "إبلاغ",
    "Block": "حظر",
    "Unblock": "رفع الحظر",
    "Follow": "متابعة",
    "Unfollow": "إلغاء المتابعة",
    "Friend": "صديق",
    "Friends": "أصدقاء",
    "Enemy": "عدو",
    "Enemies": "أعداء",
    "Ally": "حليف",
    "Allies": "حلفاء",
    "War": "حرب",
    "Peace": "سلام",
    "Treaty": "معاهدة",
    "Alliance": "تحالف",
    "Gangster": "رجل عصابة",
    "Boss": "زعيم",
    "Underboss": "نائب زعيم",
    "Capo": "كابتن",
    "Soldier": "جندي",
    "Associate": "مشارك",
    "Recruit": "مجند",
    "Don": "الدون",
    "Godfather": "العراب",
    "Mafia": "مافيا",
    "Cartel": "كارتل",
    "Syndicate": "نقابة",
    "Organization": "منظمة",
    "Family": "عائلة",
    "Respect": "احترام",
    "Power": "قوة",
    "Reputation": "سمعة",
    "Influence": "نفوذ",
    "Territory": "منطقة نفوذ",
    "Turf": "منطقة",
    "Street": "شارع",
    "City": "مدينة",
    "Country": "دولة",
    "World": "عالم",
    "Map": "خريطة",
    "Location": "موقع",
    "Coordinates": "إحداثيات",
    "North": "شمال",
    "South": "جنوب",
    "East": "شرق",
    "West": "غرب",
    "Left": "يسار",
    "Right": "يمين",
    "Up": "فوق",
    "Down": "تحت",
    "Center": "وسط",
    "Top": "أعلى",
    "Bottom": "أسفل",
    "Middle": "منتصف",
    "Start": "بداية",
    "End": "نهاية",
    "Finish": "نهاية",
    "Complete": "اكتمل",
    "Incomplete": "غير مكتمل",
    "Failed": "فشل",
    "Passed": "نجح",
    "High": "عالي",
    "Low": "منخفض",
    "Medium": "متوسط",
    "Max": "أقصى",
    "Min": "أدنى",
    "Average": "متوسط",
    "Sum": "مجموع",
    "Count": "عدد",
    "Rate": "معدل",
    "Speed": "سرعة",
    "Duration": "مدة",
    "Distance": "مسافة",
    "Area": "مساحة",
    "Volume": "حجم",
    "Weight": "وزن",
    "Height": "طول",
    "Width": "عرض",
    "Depth": "عمق",
    "Color": "لون",
    "Size": "حجم",
    "Shape": "شكل",
    "Texture": "ملمس",
    "Sound": "صوت",
    "Music": "موسيقى",
    "Video": "فيديو",
    "Audio": "صوتيات",
    "File": "ملف",
    "Folder": "مجلد",
    "Directory": "دليل",
    "Path": "مسار",
    "Link": "رابط",
    "URL": "رابط",
    "IP": "IP",
    "Port": "منفذ",
    "Protocol": "بروتوكول",
    "Host": "مضيف",
    "Domain": "نطاق",
    "DNS": "DNS",
    "HTTP": "HTTP",
    "HTTPS": "HTTPS",
    "FTP": "FTP",
    "SSH": "SSH",
    "Telnet": "Telnet",
    "SMTP": "SMTP",
    "POP3": "POP3",
    "IMAP": "IMAP",
    "TCP": "TCP",
    "UDP": "UDP",
    "Socket": "Socket",
    "Thread": "خيط",
    "Process": "عملية",
    "Memory": "ذاكرة",
    "CPU": "معالج",
    "Disk": "قرص",
    "Network": "شبكة",
    "Interface": "واجهة",
    "Driver": "تعريف",
    "Kernel": "نواة",
    "OS": "نظام تشغيل",
    "Software": "برمجيات",
    "Hardware": "عتاد",
    "Firmware": "برنامج ثابت",
    "BIOS": "BIOS",
    "Boot": "إقلاع",
    "Shutdown": "إيقاف التشغيل",
    "Restart": "إعادة تشغيل",
    "Reboot": "إعادة تشغيل",
    "Sleep": "سكون",
    "Hibernate": "إسبات",
    "Lock": "قفل",
    "Unlock": "فتح قفل",
    "Password": "كلمة المرور",
    "PIN": "PIN",
    "Key": "مفتاح",
    "Token": "رمز",
    "Session": "جلسة",
    "Cookie": "ملف تعريف ارتباط",
    "Cache": "ذاكرة مؤقتة",
    "Buffer": "مخزن مؤقت",
    "Stack": "مكدس",
    "Queue": "طابور",
    "List": "قائمة",
    "Array": "مصفوفة",
    "Vector": "متجه",
    "Map": "خريطة",
    "Set": "مجموعة",
    "Tree": "شجرة",
    "Graph": "رسم بياني",
    "Node": "عقدة",
    "Edge": "حافة",
    "Vertex": "رأس",
    "Root": "جذر",
    "Leaf": "ورقة",
    "Child": "ابن",
    "Parent": "أب",
    "Ancestor": "سلف",
    "Descendant": "خلف",
    "Sibling": "شقيق",
    "Cousin": "ابن عم",
    "Uncle": "عم",
    "Aunt": "عمة",
    "Nephew": "ابن أخ",
    "Niece": "ابنة أخ",
    "Grandparent": "جد",
    "Grandchild": "حفيد",
    "Husband": "زوج",
    "Wife": "زوجة",
    "Son": "ابن",
    "Daughter": "ابنة",
    "Brother": "أخ",
    "Sister": "أخت",
    "Father": "أب",
    "Mother": "أم",
    "Man": "رجل",
    "Woman": "امرأة",
    "Boy": "ولد",
    "Girl": "بنت",
    "Baby": "طفل",
    "Child": "طفل",
    "Teenager": "مراهق",
    "Adult": "بالغ",
    "Senior": "كبير سن",
    "Male": "ذكر",
    "Female": "أنثى",
    "Other": "آخر",
    "Gender": "جنس",
    "Sex": "جنس",
    "Age": "عمر",
    "Birth": "ميلاد",
    "Death": "وفاة",
    "Marriage": "زواج",
    "Divorce": "طلاق",
    "Single": "أعزب",
    "Married": "متزوج",
    "Divorced": "مطلق",
    "Widowed": "أرمل",
    "Separated": "منفصل",
    "Engaged": "مخطوب",
    "Relationship": "علاقة",
    "Date": "موعد",
    "Love": "حب",
    "Hate": "كره",
    "Like": "إعجاب",
    "Dislike": "عدم إعجاب",
    "Happy": "سعيد",
    "Sad": "حزين",
    "Angry": "غاضب",
    "Scared": "خائف",
    "Excited": "متحمس",
    "Bored": "ضجر",
    "Tired": "متعب",
    "Hungry": "جائع",
    "Thirsty": "عطشان",
    "Sick": "مريض",
    "Healthy": "بصحة جيدة",
    "Strong": "قوي",
    "Weak": "ضعيف",
    "Fast": "سريع",
    "Slow": "بطيء",
    "Smart": "ذكي",
    "Stupid": "غبي",
    "Rich": "غني",
    "Poor": "فقير",
    "Beautiful": "جميل",
    "Ugly": "قبيح",
    "Good": "جيد",
    "Bad": "سيء",
    "Best": "أفضل",
    "Worst": "أسوأ",
    "Better": "أفضل",
    "Worse": "أسوأ",
    "More": "أكثر",
    "Less": "أقل",
    "Most": "معظم",
    "Least": "أقل",
    "Many": "كثير",
    "Few": "قليل",
    "Some": "بعض",
    "Any": "أي",
    "No": "لا",
    "All": "كل",
    "Every": "كل",
    "Each": "كل",
    "None": "لا أحد",
    "One": "واحد",
    "Two": "اثنان",
    "Three": "ثلاثة",
    "Four": "أربعة",
    "Five": "خمسة",
    "Six": "ستة",
    "Seven": "سبعة",
    "Eight": "ثمانية",
    "Nine": "تسعة",
    "Ten": "عشرة",
    "Hundred": "مائة",
    "Thousand": "ألف",
    "Million": "مليون",
    "Billion": "مليار",
    "Trillion": "تريليون",
    "Zero": "صفر",
    "First": "أول",
    "Second": "ثاني",
    "Third": "ثالث",
    "Fourth": "رابع",
    "Fifth": "خامس",
    "Last": "أخير",
    "Next": "تالي",
    "Previous": "سابق",
    "Current": "حالي",
    "Future": "مستقبل",
    "Past": "ماضي",
    "Present": "حاضر",
    "Now": "الآن",
    "Later": "لاحقاً",
    "Soon": "قريباً",
    "Never": "أبداً",
    "Always": "دائماً",
    "Sometimes": "أحياناً",
    "Often": "غالباً",
    "Rarely": "نادراً",
    "Usually": "عادة",
    "Today": "اليوم",
    "Tomorrow": "غداً",
    "Yesterday": "أمس",
    "Morning": "صباح",
    "Noon": "ظهر",
    "Afternoon": "بعد الظهر",
    "Evening": "مساء",
    "Night": "ليل",
    "Midnight": "منتصف الليل",
    "Dawn": "فجر",
    "Sunrise": "شروق",
    "Sunset": "غروب",
    "Day": "نهار",
    "Week": "أسبوع",
    "Month": "شهر",
    "Year": "سنة",
    "Decade": "عقد",
    "Century": "قرن",
    "Millennium": "ألفية",
    "Monday": "الإثنين",
    "Tuesday": "الثلاثاء",
    "Wednesday": "الأربعاء",
    "Thursday": "الخميس",
    "Friday": "الجمعة",
    "Saturday": "السبت",
    "Sunday": "الأحد",
    "January": "يناير",
    "February": "فبراير",
    "March": "مارس",
    "April": "أبريل",
    "May": "مايو",
    "June": "يونيو",
    "July": "يوليو",
    "August": "أغسطس",
    "September": "سبتمبر",
    "October": "أكتوبر",
    "November": "نوفمبر",
    "December": "ديسمبر",
    "Spring": "ربيع",
    "Summer": "صيف",
    "Autumn": "خريف",
    "Winter": "شتاء",
    "Season": "فصل",
    "Holiday": "عطلة",
    "Vacation": "إجازة",
    "Weekend": "عطلة نهاية الأسبوع",
    "Festival": "مهرجان",
    "Party": "حفلة",
    "Event": "حدث",
    "Meeting": "اجتماع",
    "Appointment": "موعد",
    "Schedule": "جدول",
    "Calendar": "تقويم",
    "Clock": "ساعة",
    "Watch": "ساعة يد",
    "Time": "وقت",
    "Zone": "منطقة",
    "Place": "مكان",
    "Space": "فضاء",
    "Universe": "كون",
    "Galaxy": "مجرة",
    "Star": "نجم",
    "Planet": "كوكب",
    "Moon": "قمر",
    "Sun": "شمس",
    "Earth": "أرض",
    "Mars": "مريخ",
    "Venus": "زهرة",
    "Jupiter": "مشتري",
    "Saturn": "زحل",
    "Mercury": "عطارد",
    "Uranus": "أورانوس",
    "Neptune": "نبتون",
    "Pluto": "بلوتو",
    "Air": "هواء",
    "Water": "ماء",
    "Fire": "نار",
    "Wind": "رياح",
    "Rain": "مطر",
    "Snow": "ثلج",
    "Ice": "جليد",
    "Cloud": "سحابة",
    "Storm": "عاصفة",
    "Thunder": "رعد",
    "Lightning": "برق",
    "Fog": "ضباب",
    "Mist": "سديم",
    "Dew": "ندى",
    "Frost": "صقيع",
    "Hail": "برد",
    "Heat": "حرارة",
    "Coldness": "برودة",
    "Temperature": "درجة حرارة",
    "Weather": "طقس",
    "Climate": "مناخ",
    "Nature": "طبيعة",
    "Animal": "حيوان",
    "Plant": "نبات",
    "Tree": "شجرة",
    "Flower": "زهرة",
    "Grass": "عشب",
    "Leaf": "ورقة",
    "Root": "جذر",
    "Seed": "بذرة",
    "Fruit": "فاكهة",
    "Vegetable": "خضار",
    "Meat": "لحم",
    "Fish": "سمك",
    "Bird": "طائر",
    "Insect": "حشرة",
    "Dog": "كلب",
    "Cat": "قطة",
    "Horse": "حصان",
    "Cow": "بقرة",
    "Pig": "خنزير",
    "Sheep": "خروف",
    "Goat": "ماعز",
    "Chicken": "دجاجة",
    "Duck": "بطة",
    "Goose": "وزة",
    "Rabbit": "أرنب",
    "Mouse": "فأر",
    "Rat": "جرذ",
    "Lion": "أسد",
    "Tiger": "نمر",
    "Bear": "دب",
    "Wolf": "ذئب",
    "Fox": "ثعلب",
    "Elephant": "فيل",
    "Giraffe": "زرافة",
    "Monkey": "قرد",
    "Snake": "ثعبان",
    "Lizard": "سحلية",
    "Frog": "ضفدع",
    "Spider": "عنكبوت",
    "Fly": "ذبابة",
    "Bee": "نحلة",
    "Ant": "نملة",
    "Mosquito": "بعوضة",
    "Butterfly": "فراشة",
    "Worm": "دودة",
    "Shark": "قرش",
    "Whale": "حوت",
    "Dolphin": "دلفين",
    "Crab": "سرطان",
    "Lobster": "كركند",
    "Shrimp": "روبيان",
    "Octopus": "أخطبوط",
    "Squid": "حبار",
    "Jellyfish": "قنديل بحر",
    "Starfish": "نجم البحر",
    "Coral": "مرجان",
    "Shell": "صدفة",
    "Pearl": "لؤلؤة",
    "Gold": "ذهب",
    "Silver": "فضة",
    "Bronze": "برونز",
    "Iron": "حديد",
    "Steel": "فولاذ",
    "Copper": "نحاس",
    "Aluminum": "ألمنيوم",
    "Lead": "رصاص",
    "Tin": "قصدير",
    "Zinc": "زنك",
    "Nickel": "نيكل",
    "Chrome": "كروم",
    "Titanium": "تيتانيوم",
    "Platinum": "بلاتين",
    "Diamond": "ماس",
    "Ruby": "ياقوت أحمر",
    "Emerald": "زمرد",
    "Sapphire": "ياقوت أزرق",
    "Topaz": "توباز",
    "Amethyst": "جمشت",
    "Opal": "أوبال",
    "Jade": "يشم",
    "Amber": "كهرمان",
    "Crystal": "كريستال",
    "Glass": "زجاج",
    "Plastic": "بلاستيك",
    "Rubber": "مطاط",
    "Wood": "خشب",
    "Paper": "ورق",
    "Cardboard": "كرتون",
    "Cloth": "قماش",
    "Fabric": "نسيج",
    "Leather": "جلد",
    "Fur": "فراء",
    "Wool": "صوف",
    "Cotton": "قطن",
    "Silk": "حرير",
    "Linen": "كتان",
    "Nylon": "نايلون",
    "Polyester": "بوليستر",
    "Stone": "حجر",
    "Rock": "صخر",
    "Sand": "رمل",
    "Dust": "غبار",
    "Mud": "طين",
    "Clay": "صلصال",
    "Soil": "تربة",
    "Dirt": "وسخ",
    "Ash": "رماد",
    "Smoke": "دخان",
    "Steam": "بخار",
    "Gas": "غاز",
    "Oil": "نفط",
    "Fuel": "وقود",
    "Petrol": "بنزين",
    "Diesel": "ديزل",
    "Coal": "فحم",
    "Charcoal": "فحم نباتي",
    "Firewood": "حطب",
    "Electricity": "كهرباء",
    "Energy": "طاقة",
    "Power": "قدرة",
    "Force": "قوة",
    "Pressure": "ضغط",
    "Gravity": "جاذبية",
    "Magnetism": "مغناطيسية",
    "Radiation": "إشعاع",
    "Light": "ضوء",
    "Darkness": "ظلام",
    "Shadow": "ظل",
    "Reflection": "انعكاس",
    "Refraction": "انكسار",
    "Color": "لون",
    "Red": "أحمر",
    "Green": "أخضر",
    "Blue": "أزرق",
    "Yellow": "أصفر",
    "Orange": "برتقالي",
    "Purple": "أرجواني",
    "Violet": "بنفسجي",
    "Pink": "وردي",
    "Brown": "بني",
    "Black": "أسود",
    "White": "أبيض",
    "Gray": "رمادي",
    "Cyan": "سماوي",
    "Magenta": "أرجواني فاتح",
    "Indigo": "نيلي",
    "Turquoise": "فيروزي",
    "Beige": "بيج",
    "Maroon": "كستنائي",
    "Navy": "بحري",
    "Olive": "زيتوني",
    "Teal": "أزرق مخضر",
    "Lime": "ليموني",
    "CoralColor": "مرجاني",
    "Salmon": "سلموني",
    "Khaki": "كاكي",
    "Lavender": "خزامي",
    "Crimson": "قرمزي",
    "Scarlet": "قرمزي فاقع",
    "Azure": "لازوردي",
    "Ivory": "عاجي",
    "Cream": "كريمي",
    "Golden": "ذهبي",
    "Silvery": "فضي",
    "BronzeColor": "برونزي",
    "Metallic": "معدني",
    "Transparent": "شفاف",
    "Opaque": "معتم",
    "Bright": "ساطع",
    "Dim": "خافت",
    "Dark": "داكن",
    "LightColor": "فاتح",
    "Shiny": "لامع",
    "Dull": "باهت",
    "Clear": "واضح",
    "Blurry": "ضبابي",
    "Sharp": "حاد",
    "Soft": "ناعم",
    "Hard": "صلب",
    "Rough": "خشن",
    "Smooth": "أملس",
    "Wet": "مبلل",
    "Dry": "جاف",
    "Hot": "حار",
    "Cold": "بارد",
    "Warm": "دافئ",
    "Cool": "بارد قليلاً",
    "Fresh": "طازج",
    "Rotten": "فاسد",
    "Sweet": "حلو",
    "Sour": "حامض",
    "Bitter": "مر",
    "Salty": "مالح",
    "Spicy": "حار",
    "Savory": "لذيذ",
    "Tasty": "طعم جيد",
    "Delicious": "شهي",
    "Disgusting": "مقرف",
    "Smell": "رائحة",
    "Fragrance": "أريج",
    "Perfume": "عطر",
    "Stink": "نتانة",
    "Odor": "رائحة كريهة",
    "Scent": "شذى",
    "Aroma": "عبق",
    "Taste": "مذاق",
    "Flavor": "نكهة",
    "Touch": "لمس",
    "Feeling": "شعور",
    "Sensation": "إحساس",
    "Pain": "ألم",
    "Pleasure": "متعة",
    "Comfort": "راحة",
    "Discomfort": "عدم راحة",
    "Itch": "حكة",
    "Tickle": "دغدغة",
    "Burn": "حرق",
    "Freeze": "تجميد",
    "Shock": "صدمة",
    "Vibration": "اهتزاز",
    "Motion": "حركة",
    "Movement": "تحرك",
    "Speed": "سرعة",
    "Velocity": "سرعة متجهة",
    "Acceleration": "تسارع",
    "Deceleration": "تباطؤ",
    "Momentum": "زخم",
    "Inertia": "قصور ذاتي",
    "Friction": "احتكاك",
    "Resistance": "مقاومة",
    "Tension": "توتر",
    "Compression": "ضغط",
    "Shear": "قص",
    "Torsion": "لي",
    "Bending": "انحناء",
    "Stress": "إجهاد",
    "Strain": "انفعال",
    "Strength": "قوة",
    "Durability": "متانة",
    "Elasticity": "مرونة",
    "Plasticity": "لدونة",
    "Hardness": "صلادة",
    "Toughness": "متانة",
    "Brittleness": "هشاشة",
    "Ductility": "مطيلية",
    "Malleability": "طرقية",
    "Conductivity": "توصيلية",
    "Resistivity": "مقاومية",
    "Density": "كثافة",
    "Viscosity": "لزوجة",
    "Fluidity": "سيولة",
    "Solubility": "ذوبانية",
    "Concentration": "تركيز",
    "Dilution": "تخفيف",
    "Saturation": "تشبع",
    "Precipitation": "ترسب",
    "Evaporation": "تبخر",
    "Condensation": "تكثف",
    "Sublimation": "تسامي",
    "Deposition": "ترسب",
    "Fusion": "انصهار",
    "Fission": "انشطار",
    "Reaction": "تفاعل",
    "Synthesis": "تصنيع",
    "Analysis": "تحليل",
    "Experiment": "تجربة",
    "Observation": "ملاحظة",
    "Hypothesis": "فرضية",
    "Theory": "نظرية",
    "Law": "قانون",
    "Principle": "مبدأ",
    "Fact": "حقيقة",
    "Truth": "صدق",
    "Lie": "كذب",
    "Belief": "اعتقاد",
    "Opinion": "رأي",
    "Idea": "فكرة",
    "Concept": "مفهوم",
    "Thought": "فكر",
    "Mind": "عقل",
    "Brain": "دماغ",
    "Soul": "روح",
    "Spirit": "روح",
    "Ghost": "شبح",
    "Angel": "ملاك",
    "Demon": "شيطان",
    "God": "إله",
    "Religion": "دين",
    "Faith": "إيمان",
    "Hope": "أمل",
    "Charity": "إحسان",
    "Justice": "عدالة",
    "Freedom": "حرية",
    "Liberty": "حرية",
    "Equality": "مساواة",
    "Fraternity": "إخاء",
    "Peace": "سلام",
    "War": "حرب",
    "Conflict": "صراع",
    "Battle": "معركة",
    "Fight": "قتال",
    "Struggle": "نضال",
    "Victory": "نصر",
    "Defeat": "هزيمة",
    "Surrender": "استسلام",
    "Truce": "هدنة",
    "Treaty": "معاهدة",
    "Alliance": "تحالف",
    "Union": "اتحاد",
    "League": "رابطة",
    "Association": "جمعية",
    "Organization": "منظمة",
    "Institution": "مؤسسة",
    "Company": "شركة",
    "Corporation": "مؤسسة تجارية",
    "Business": "عمل تجاري",
    "Industry": "صناعة",
    "Factory": "مصنع",
    "IndustrialPlant": "منشأة",
    "Workshop": "ورشة",
    "Office": "مكتب",
    "Store": "محل",
    "Bazaar": "بازار",
    "Mall": "مركز تسوق",
    "Supermarket": "سوبر ماركت",
    "Grocery": "بقالة",
    "Restaurant": "مطعم",
    "Cafe": "مقهى",
    "Bar": "حانة",
    "Pub": "حانة",
    "Club": "نادي",
    "Hotel": "فندق",
    "Motel": "نزل",
    "Inn": "خان",
    "Hostel": "بيت شباب",
    "Resort": "منتجع",
    "Park": "حديقة",
    "Garden": "بستان",
    "Forest": "غابة",
    "Jungle": "أدغال",
    "Desert": "صحراء",
    "Mountain": "جبل",
    "Hill": "تل",
    "Valley": "وادي",
    "Plain": "سهل",
    "Plateau": "هضبة",
    "Canyon": "أخدود",
    "Cave": "كهف",
    "River": "نهر",
    "Lake": "بحيرة",
    "Pond": "بركة",
    "Sea": "بحر",
    "Ocean": "محيط",
    "Beach": "شاطئ",
    "Coast": "ساحل",
    "Island": "جزيرة",
    "Peninsula": "شبه جزيرة",
    "Continent": "قارة",
    "Country": "دولة",
    "State": "ولاية",
    "Province": "مقاطعة",
    "City": "مدينة",
    "Town": "بلدة",
    "Village": "قرية",
    "Neighborhood": "حي",
    "Street": "شارع",
    "Road": "طريق",
    "Highway": "طريق سريع",
    "Bridge": "جسر",
    "Tunnel": "نفق",
    "Building": "مبنى",
    "House": "منزل",
    "Apartment": "شقة",
    "Room": "غرفة",
    "Kitchen": "مطبخ",
    "Bathroom": "حمام",
    "Bedroom": "غرفة نوم",
    "Living Room": "غرفة معيشة",
    "Dining Room": "غرفة طعام",
    "Garage": "كراج",
    "Basement": "قبو",
    "Attic": "علية",
    "Roof": "سقف",
    "Floor": "أرضية",
    "Wall": "جدار",
    "Window": "نافذة",
    "Door": "باب",
    "Furniture": "أثاث",
    "Table": "طاولة",
    "Chair": "كرسي",
    "Sofa": "أريكة",
    "Bed": "سرير",
    "Desk": "مكتب",
    "Cabinet": "خزانة",
    "Shelf": "رف",
    "Lamp": "مصباح",
    "Appliance": "جهاز منزلي",
    "Refrigerator": "ثلاجة",
    "Stove": "موقد",
    "Oven": "فرن",
    "Microwave": "ميكروويف",
    "Washer": "غسالة",
    "Dryer": "نشافة",
    "Dishwasher": "غسالة صحون",
    "Computer": "حاسوب",
    "Laptop": "لابتوب",
    "Tablet": "تابلت",
    "Phone": "هاتف",
    "Television": "تلفاز",
    "Radio": "راديو",
    "Camera": "كاميرا",
    "Tool": "أداة",
    "Hammer": "مطرقة",
    "Screwdriver": "مفك",
    "Wrench": "مفتاح ربط",
    "Saw": "منشار",
    "Drill": "مقدح",
    "Nail": "مسمار",
    "Screw": "برغي",
    "Bolt": "برغي بصمولة",
    "Nut": "صمولة",
    "Vehicle": "مركبة",
    "Car": "سيارة",
    "Truck": "شاحنة",
    "Bus": "حافلة",
    "Motorcycle": "دراجة نارية",
    "Bicycle": "دراجة هوائية",
    "Train": "قطار",
    "Airplane": "طائرة",
    "Helicopter": "مروحية",
    "Boat": "قارب",
    "Ship": "سفينة",
    "Submarine": "غواصة",
    "Rocket": "صاروخ",
    "Spaceship": "سفينة فضاء"}


def update_po_file():
    if not os.path.exists(PO_FILE):
        print(f"Error: PO file not found at {PO_FILE}")
        return

    try:
        with open(PO_FILE, 'r', encoding='utf-8') as f:
            lines = f.readlines()

        new_lines = []
        count = 0
        i = 0
        while i < len(lines):
            line = lines[i]

            # Check for msgid "WORD"
            # We assume simple one-line msgid for these common terms
            msgid_match = re.match(r'^msgid "(.*)"$', line.strip())

            if msgid_match:
                msgid = msgid_match.group(1)

                # Look ahead for msgstr ""
                if i + 1 < len(lines):
                    next_line = lines[i + 1]
                    msgstr_match = re.match(r'^msgstr ""$', next_line.strip())

                    if msgstr_match and msgid in COMMON_TRANSLATIONS:
                        translation = COMMON_TRANSLATIONS[msgid]
                        # Replace msgstr "" with msgstr "TRANSLATION"
                        new_lines.append(line)
                        new_lines.append(f'msgstr "{translation}"\n')
                        count += 1
                        print(f"Translated '{msgid}' -> '{translation}'")
                        i += 2
                        continue

            new_lines.append(line)
            i += 1

        with open(PO_FILE, 'w', encoding='utf-8') as f:
            f.writelines(new_lines)

        print(f"Successfully updated {count} translations in {PO_FILE}")

    except Exception as e:
        print(f"Error updating PO file: {e}")


if __name__ == "__main__":
    update_po_file()
